# Generated by Django 6.0.4 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contentblock_cta_link_contentblock_cta_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="herobanner",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
