# Generated by Django 6.0.4 on 2026-05-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_path", models.CharField(max_length=255, unique=True)),
                ("destination_path", models.CharField(max_length=255)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(301, "Permanent (301)"), (302, "Temporary (302)")],
                        default=301,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SEOMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("canonical_url", models.URLField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=255, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("og_image", models.URLField(blank=True, null=True)),
                ("index", models.BooleanField(default=True)),
                ("follow", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Metadata",
                "verbose_name_plural": "SEO Metadata",
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
